name: Tests

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester
      run: Install-Module Pester -Force -Scope CurrentUser
      shell: pwsh
    - name: Run Tests
      run: Invoke-Pester -EnableExit
      shell: pwsh
